markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
structuredTasks: true
searchTools:
  toolMappingsFile: "bmad-core/data/tool-mappings.yaml"
  defaultOutputFile: "search-tools.yaml"
validationSchemas:
  storyContractSchema: "schemas/story-contract-schema.json"
  architectureSchema: "schemas/architecture-schema.json"
  prdSchema: "schemas/prd-schema.json"
  checklistSchema: "schemas/checklist-schema.json"
  taskSchema: "schemas/task-schema.json"
  structuredTaskSchema: "schemas/structured-task-schema.json"
