id: brownfield-create-story
name: Create Brownfield Story Task
purpose: Create a single user story for very small brownfield enhancements that can be completed in one focused development session. This task is for minimal additions or bug fixes that require existing system integration awareness.

steps:
  step0: |
    Initialize Memory and Context
    - Initialize working memory for brownfield story creation
    - Retrieve any previous brownfield story patterns and integration approaches
    - Set up context for existing system understanding
  
  step1: |
    Quick Project Assessment
    - Gather minimal but essential context about the existing project
    - Identify relevant existing functionality
    - Note technology stack for the area
    - Understand integration points clearly
    - Identify existing patterns for similar work
    - Define specific change clearly
    - Identify impact boundaries
    - Establish success criteria
  
  step2: |
    Story Creation
    - Create a single focused story with proper structure
    - Include Story Title, User Story, Story Context
    - Define Acceptance Criteria with functional, integration, and quality requirements
    - Add Technical Notes and Definition of Done
    - Ensure story integrates with existing components/systems
    - Specify technology stack and patterns to follow
  
  step3: |
    Risk and Compatibility Check
    - Assess primary risk to existing system
    - Define simple mitigation approach
    - Plan rollback strategy if needed
    - Verify no breaking changes to existing APIs
    - Ensure database changes (if any) are additive only
    - Confirm UI changes follow existing design patterns
    - Check performance impact is negligible
  
  step4: |
    Validation Checklist
    - Confirm story can be completed in one development session
    - Verify integration approach is straightforward
    - Ensure story follows existing patterns exactly
    - Check no design or architecture work required
    - Validate story requirements are unambiguous
    - Confirm integration points are clearly specified
    - Ensure success criteria are testable
    - Verify rollback approach is simple

metadata:
  executionMode: SEQUENTIAL
  requiresWorkingMemory: true
  taskType: brownfield-story-creation
  
notes: |
  - This task is for VERY SMALL brownfield changes only
  - If complexity grows during analysis, escalate to brownfield-create-epic
  - Always prioritize existing system integrity
  - When in doubt about integration complexity, use brownfield-create-epic instead
  - Stories should take no more than 4 hours of focused development work