id: execute-task-with-adaptation
name: Execute Task with Dynamic Plan Adaptation
purpose: Execute a task file with automatic complexity analysis and sub-task creation
notes: This task demonstrates how to use the task runner to execute tasks with dynamic plan adaptation

steps:
  step0: |
    Initialize working memory and Task Runner
    - Import the TaskRunner from tools/task-runner.js
    - Create a new TaskRunner instance with the project root directory
    - Verify agent has working memory initialized
  
  step1: |
    Load and Analyze Task
    - Use taskRunner.executeTask() with the agent name and task path
    - The runner will automatically apply planAdaptation() to check complexity
    - Log whether the task was split into sub-tasks
  
  step2: |
    Process Sub-tasks (if created)
    - Iterate through each sub-task in the adapted plan
    - Use taskRunner.executeSubTask() to start each sub-task
    - Execute the sub-task steps
    - Use taskRunner.completeSubTask() when done
  
  step3: |
    Update Progress in working memory
    - Record observations for each completed step
    - Update the current step pointer
    - Maintain context for future reference
  
  step4: |
    Handle Dynamic Complexity
    - If encountering unexpected complexity, use insertSubTask()
    - Provide clear title and steps for the new sub-task
    - Continue execution with the updated plan

metadata:
  executionMode: SEQUENTIAL
  requiresWorkingMemory: true
  supportsAdaptation: true